export const faqs = [
  {
    question:
      "I would like new features and enhancements and provide other feedback. How do I provide feedback?",
    answer:
      "Use the feedback icon at the bottom of the prompt response (next to the copy icon) to submit your suggestions or feedback. Send feedback to NIAMS SITB IT Pilot Mailbox.",
  },
  {
    question: "I’m unable to get the response I want. How do I get support?",
    answer:
      "If you're having trouble, please contact NIAMS SITB IT Pilot Mailbox for assistance.",
  },
  {
    question: "How is this different from ChatGPT?",
    answer:
      "This is a custom application built on top of FedRAMP High certified Azure OpenAI services. All your data is securely stored within the NIAMS subscription and is not shared with other NIH Institutes or Centers, Microsoft, or any external entities.",
  },
  {
    question: "Will there be more updates to this application?",
    answer:
      "Yes, we plan to continue improving the application. Please provide your feedback by emailing NIAMS SITB IT Pilot Mailbox or by clicking on the feedback icon at the bottom right corner of the chatbot response.",
  },
  {
    question:
      "I think this is a good start, but it would be more useful if we could make this more NIAMS-specific or allow me to set the context to my area of research or my knowledge base of documents/articles/publications. How can I do that?",
    answer:
      "Future enhancements can incorporate these features. Please provide detailed feedback on what would be most useful to you.",
  },
  {
    question:
      "Can this crawl web sources like PubMed and answer specific questions?",
    answer:
      "This is a potential enhancement that could be considered in the future. Please provide detailed and specific feedback on what features would add the most value to you.",
  },
  {
    question: "How do I write effective prompts to get the best responses?",
    answer:
      "Writing clear, specific, and descriptive prompts helps the chatbot understand your needs better. Refer to our guide on the Best Practices for Writing Prompts for detailed tips and examples.",
  },
  {
    question: "Is my data secure when using this chatbot?",
    answer:
      "Yes, your data is fully secure. It is stored within the NIAMS environment on Azure OpenAI services and is not shared with any third parties or external entities.",
  },
  {
    question:
      "Can I use this chatbot to access NIH-specific databases or internal documents?",
    answer:
      "Currently, the chatbot is focused on general AI-powered responses. However, we are considering future updates that could integrate NIH-specific databases or internal document access. Please share your feedback if this feature would be valuable to you.",
  },
  {
    question:
      "What should I do if the chatbot generates inaccurate or incomplete information?",
    answer:
      "While we strive for accuracy, the chatbot may occasionally generate incorrect information. If this happens, please cross-check the information with other reliable sources and report the issue using the feedback button. Ensure that the content generated is suitable for your specific context before using or sharing it.",
  },
  {
    question: "What file types can I upload to the NIAMS AI Chatbot?",
    answer:
      "The NIAMS AI Chatbot currently supports the following file types for upload: .pdf, .json, .docx, .txt, .md, .xml. However, it does not currently support .pptx, video files, .xlsx, images, or .csv files.",
  },
  {
    question:
      "How accurate are the responses generated by the NIAMS AI Chatbot?",
    answer:
      "The accuracy of the chatbot's responses may vary depending on the complexity of the query and the specific knowledge programmed into the AI models. Users are responsible for verifying the accuracy, completeness, and relevance of any output before using it in their work.",
  },
  {
    question:
      "Can the NIAMS AI Chatbot be used for other applications beyond answering questions?",
    answer:
      "Yes, the platform on which the NIAMS AI Chatbot is built can be leveraged for a variety of applications, including natural language processing, machine learning tasks, and generating human-like text responses. This framework is designed to support future use cases that align with NIAMS’s needs.",
  },
  {
    question: "How does the NIAMS AI Chatbot ensure security and compliance?",
    answer:
      "The NIAMS AI Chatbot is hosted on Microsoft Azure's OpenAI service, which adheres to the Federal Risk and Authorization Management Program (FedRAMP) standards. This ensures that all interactions are conducted within a secure and compliant cloud environment, prioritizing the protection of sensitive information.",
  },
];
