import React from 'react';
import { FiAlertTriangle, FiChevronRight, FiBookOpen, FiMessageCircle, FiRepeat, FiUserCheck, FiCpu, FiInfo } from 'react-icons/fi';
import PromptsAndInteractions from '../components/PromptsAndInteractions';

const Overview: React.FC = () => {
  return (
    <div className="p-6 bg-gray-50 min-h-screen">
      <div className="max-w-5xl mx-auto">
        <div className="p-8">
         {/* Overview Section - Blended with Background */}
         <h1 className="text-3xl font-bold mb-6 text-gray-800">Overview of the NIAMS Artificial Intelligence (AI) Chat</h1>
          <p className="text-gray-600 mb-6">
          The NIAMS AI Chatbot (AI Chat) pilot, aims to establish a secure and private environment and experience for NIAMS staff when interacting with LLM artificial intelligence (AI) models. The focus is to help NIAMS staff understand how to leverage AI as part of their daily tasks and help NIAMS understand the associated costs.  Leveraging the Microsoft Azure OpenAI service brings the advanced capabilities of OpenAI's artificial intelligence models, including the renowned GPT (Generative Pre-trained Transformer) technology, to NIAMS staff within a secure and compliant cloud environment. Specifically tailored for U.S. government agencies and their partners, this service adheres to the <b>Federal Risk and Authorization Management Program (FedRAMP)</b> standards, ensuring that it meets strict security and compliance requirements.
          <br /><br />
          By establishing the secured NIAMS AI platform (which the NIAMS AI Chat uses), this platform can be leveraged for other use cases in the future. This platform allows NIAMS to leverage the power of AI for a variety of applications—ranging from natural language processing, machine learning tasks, to generating human-like text responses—within a framework that prioritizes the protection of sensitive information. This integration combines the innovative AI capabilities of OpenAI with Azure's robust cloud infrastructure, offering a powerful tool for enhancing efficiency, innovation, and decision-making processes, all while maintaining high standards of security and compliance
           <br /><br />
           It's important to note that while the NIAMS AI Chat can handle a diverse array of queries, the quality and accuracy of responses may vary based on the complexity of the question and the specific knowledge programmed into the AI models. Each user is responsible for ensuring the accuracy, completeness, and relevance of any output generated by the NIAMS AI Chat and how the generated output is used.
           </p>
           <div className="bg-red-50 p-4 rounded-md border-l-4 border-red-500 mt-6">
          <div className="flex items-start">
            <FiAlertTriangle className="text-red-600 text-2xl mr-3" />
            <div>
              <p className="text-gray-700">
              <strong>Disclaimer: </strong>You are responsible for ensuring the accuracy, completeness, and relevance of any output generated by this tool and how the generated output is used. You should always independently understand and verify the content generated is accurate and suitable for your use. Please make any necessary edits before sharing the output from this tool.
              </p>
             
            </div>
          </div>
        </div>
        <br></br>

          {/* Limitation Alert - Blended */}
          <div className="bg-yellow-50 p-4 rounded-md border-l-4 border-yellow-500 mb-6">
            <div className="flex items-start">
              <FiAlertTriangle className="text-yellow-600 text-2xl mr-3" />
              <div>
                <h3 className="text-lg font-semibold text-gray-700">Current Limitations of Document Upload</h3>
                <p className="text-gray-600 mt-1">
                  The platform currently supports files such as <i>.pdf, .json, .docx, .txt, .md,</i> and <i>.xml</i>, but does not support <i>.pptx,</i> video files, <i>.xlsx,</i> images, or <i>.csv</i> files.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Overview;
